export const tailwindcssTokens = {
  buttons: {
    'primary': ' bg-blue-500 border border-blue-500 text-white rounded ',
    'secondary': ' bg-gray-500 border border-gray-500 text-white rounded ',
    'success': ' bg-green-500 border border-green-500 text-white rounded ',
    'danger': ' bg-red-500 border border-red-500 text-white rounded ',
    'warning': ' bg-yellow-500 border border-yellow-500 text-white rounded ',
    'info': ' bg-teal-500 border border-teal-500 text-white rounded ',
    'light': ' bg-gray-200 border border-gray-200 text-gray-800 rounded ',
    'dark': ' bg-gray-700 border border-gray-500 text-white rounded ',
    'link': ' bg-transparent border border-transparent text-blue-500 font-semibold ',
    'outline-primary': ' bg-transparent border border-blue-500 text-blue-500 rounded ',
    'outline-secondary': ' bg-transparent border border-gray-500 text-gray-500 rounded ',
    'outline-success': ' bg-transparent border border-green-500 text-green-500 rounded ',
    'outline-danger': ' bg-transparent border border-red-500 text-red-500 rounded ',
    'outline-warning': ' bg-transparent border border-yellow-500 text-yellow-500 rounded ',
    'outline-info': ' bg-transparent border border-teal-500 text-teal-500 rounded ',
    'outline-light': ' bg-transparent border border-gray-200 text-gray-200 rounded ',
    'outline-dark': ' bg-transparent border border-gray-800 text-gray-800 rounded ',
    hovers: {
      'primary': ' hover:bg-blue-700 hover:border-blue-700 ',
      'secondary': ' hover:bg-gray-700 hover:border-gray-700 ',
      'success': ' hover:bg-green-700 hover:border-green-700 ',
      'danger': ' hover:bg-red-700 hover:border-red-700 ',
      'warning': ' hover:bg-yellow-700 hover:border-yellow-700 ',
      'info': ' hover:bg-teal-700 hover:border-teal-700 ',
      'light': ' hover:bg-gray-400 hover:border-gray-400 ',
      'dark': ' hover:bg-gray-900 hover:border-gray-700 ',
      'link': ' hover:text-blue-700 ',
      'outline-primary': ' hover:bg-blue-500 hover:text-white ',
      'outline-secondary': ' hover:bg-gray-500 hover:text-white ',
      'outline-success': ' hover:bg-green-500 hover:text-white ',
      'outline-danger': ' hover:bg-red-500 hover:text-white ',
      'outline-warning': ' hover:bg-yellow-500 hover:text-white ',
      'outline-info': ' hover:bg-teal-500 hover:text-white ',
      'outline-light': ' hover:bg-gray-200 hover:text-gray-800 ',
      'outline-dark': ' hover:bg-gray-800 hover:text-white ',
    },
    sizes: {
      'sm': ' py-1 px-2 ',
      'md': ' py-2 px-4 ',
      'lg': ' font-semibold py-3 px-6 ',
    },
    disabled: ' opacity-50 cursor-not-allowed ',
  },
};